-- REAA Ultimate v4.0 — Supabase schema
-- Run this in: Supabase Dashboard → SQL Editor → New query → Run

create table if not exists leads (
  id          bigint generated by default as identity primary key,
  name        text not null,
  phone       text not null,
  email       text,
  source      text,
  keyword     text,
  language    text default 'English',
  status      text default 'new',
  score       int,
  created_at  timestamptz default now()
);

create table if not exists listings (
  id          bigint generated by default as identity primary key,
  address     text not null,
  price       numeric,
  beds        int,
  baths       numeric,
  sqft        int,
  type        text,
  area        text,
  status      text default 'active',
  created_at  timestamptz default now()
);

create table if not exists songs (
  id          bigint generated by default as identity primary key,
  address     text not null,
  genre       text,
  language    text,
  title       text,
  lyrics_json jsonb,
  created_at  timestamptz default now()
);

create table if not exists content_calendar (
  id            bigint generated by default as identity primary key,
  date          date,
  platform      text,
  content_type  text,
  script        text,
  status        text default 'draft',
  posted_at     timestamptz,
  created_at    timestamptz default now()
);

create table if not exists broadcasts (
  id          bigint generated by default as identity primary key,
  segment     text,
  message     text,
  sent_count  int default 0,
  sent_at     timestamptz,
  created_at  timestamptz default now()
);

create index if not exists leads_created_at_idx on leads (created_at desc);
create index if not exists songs_created_at_idx on songs (created_at desc);
create index if not exists listings_area_idx on listings (area);

-- ─────────────────────────────────────────────────────────────
-- Row Level Security
--
-- The anon key is public by design — anyone who loads the app can read it.
-- RLS is what actually controls access. It is enabled below with NO policies,
-- which denies everything to anon. The backend uses the anon key today, so
-- writes will fail until you either:
--
--   (a) give the backend a SERVICE_ROLE key (it bypasses RLS), or
--   (b) add explicit policies for the operations you want to allow.
--
-- Left closed on purpose: opening these tables to anon would let anyone on
-- the internet read every lead in the CRM.
-- ─────────────────────────────────────────────────────────────

alter table leads             enable row level security;
alter table listings          enable row level security;
alter table songs             enable row level security;
alter table content_calendar  enable row level security;
alter table broadcasts        enable row level security;
